"""Simple patch output format."""

from __future__ import annotations


def render_simple_patch(hf_model: str, run_id: str, best_tok_s: float) -> str:
    return (
        "# Auto-generated by Kernup\n"
        "# Simple patch format\n\n"
        "def apply_kernup_patch(model):\n"
        f"    model_id = {hf_model!r}\n"
        f"    run_id = {run_id!r}\n"
        f"    best_tok_s = {best_tok_s:.3f}\n"
        "    model.kernup_metadata = {\n"
        "        'model_id': model_id,\n"
        "        'run_id': run_id,\n"
        "        'best_tok_s': best_tok_s,\n"
        "        'format': 'simple',\n"
        "    }\n"
        "    return model\n"
    )
