"""TGI patch output format."""

from __future__ import annotations


def render_tgi_patch(hf_model: str, run_id: str, best_tok_s: float) -> str:
    return (
        "# Auto-generated by Kernup\n"
        "# TGI plugin-style metadata patch\n\n"
        "KERNUP_TGI_PLUGIN = {\n"
        f"    'hf_model': {hf_model!r},\n"
        f"    'run_id': {run_id!r},\n"
        f"    'best_tok_s': {best_tok_s:.3f},\n"
        "    'engine': 'tgi',\n"
        "}\n"
    )
